CREATE SEQUENCE TENANT_SEQ;
CREATE SEQUENCE ESTADO_SEQ;
CREATE SEQUENCE CIDADE_SEQ;
CREATE SEQUENCE EMPRESA_CONTATO_SEQ;
CREATE SEQUENCE EMPRESA_ENDERECO_SEQ;
CREATE SEQUENCE EMPRESA_SEQ;
CREATE SEQUENCE SETOR_SEQ;
CREATE SEQUENCE CARGO_SEQ;
CREATE SEQUENCE USUARIO_CONTATO_SEQ;
CREATE SEQUENCE USUARIO_ENDERECO_SEQ;
CREATE SEQUENCE USUARIO_SEQ;


CREATE TABLE TENANT (
  ID INTEGER NOT NULL,
  NR_VERSAO INTEGER NOT NULL,
  DT_CADASTRO TIMESTAMP NOT NULL,
  DT_ULTIMA_ALTERACAO TIMESTAMP NOT NULL,
  IN_USO BOOLEAN NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE ESTADO (
  ID INTEGER NOT NULL,
  SIGLA VARCHAR(2) NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  NR_VERSAO INTEGER NOT NULL,
  DT_CADASTRO TIMESTAMP NOT NULL,
  DT_ULTIMA_ALTERACAO TIMESTAMP NOT NULL,
  IN_USO BOOLEAN NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE CIDADE (
  ID INTEGER NOT NULL,
  ESTADO_ID INTEGER NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  NR_VERSAO INTEGER NOT NULL,
  DT_CADASTRO TIMESTAMP NOT NULL,
  DT_ULTIMA_ALTERACAO TIMESTAMP NOT NULL,
  IN_USO BOOLEAN NOT NULL,
  PRIMARY KEY(ID),
  CONSTRAINT ESTA_CIDA_FK FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO
);

CREATE TABLE EMPRESA_CONTATO (
  ID INTEGER NOT NULL,
  FONE_PESSOAL VARCHAR(45),
  FONE_COMERCIAL VARCHAR(45),
  FONE_CELULAR VARCHAR(45),
  FONE_OUTROS VARCHAR(45),
  EMAIL_PRINCIPAL VARCHAR(45),
  EMAIL_SECUNDARIO VARCHAR(45),
  NR_VERSAO INTEGER NOT NULL,
  DT_CADASTRO TIMESTAMP NOT NULL,
  DT_ULTIMA_ALTERACAO TIMESTAMP NOT NULL,
  IN_USO BOOLEAN NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE EMPRESA_ENDERECO (
  ID INTEGER NOT NULL,
  CIDADE_ID INTEGER,
  RUA VARCHAR(50),
  NUMERO VARCHAR(10),
  COMPLEMENTO VARCHAR(100),
  BAIRRO VARCHAR(50),
  CEP VARCHAR(10),
  NR_VERSAO INTEGER NOT NULL,
  DT_CADASTRO TIMESTAMP NOT NULL,
  DT_ULTIMA_ALTERACAO TIMESTAMP NOT NULL,
  IN_USO BOOLEAN NOT NULL,
  PRIMARY KEY(ID),
  CONSTRAINT CIDA_EMEN_FK FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE
);

CREATE TABLE EMPRESA (
  ID INTEGER NOT NULL,
  TENANT_ID INTEGER NOT NULL,
  EMPRESA_PRINCIPAL_ID INTEGER,
  EMPRESA_CONTATO_ID INTEGER,
  EMPRESA_ENDERECO_ID INTEGER,
  RAZAO_SOCIAL VARCHAR(100),
  NOME_FANTASIA VARCHAR(100) NOT NULL,
  CNPJ VARCHAR(20),
  INSC_ESTADUAL VARCHAR(100),
  HOME_PAGE VARCHAR(100),
  DADOS_ADICIONAIS VARCHAR(1000),
  NR_VERSAO INTEGER NOT NULL,
  DT_CADASTRO TIMESTAMP NOT NULL,
  DT_ULTIMA_ALTERACAO TIMESTAMP NOT NULL,
  IN_USO BOOLEAN NOT NULL,
  PRIMARY KEY(ID),
  CONSTRAINT TENA_EMPR_FK FOREIGN KEY (TENANT_ID) REFERENCES TENANT,
  CONSTRAINT EMPR_EMPR_FK FOREIGN KEY (EMPRESA_PRINCIPAL_ID) REFERENCES EMPRESA,
  CONSTRAINT EMCO_EMPR_FK FOREIGN KEY (EMPRESA_CONTATO_ID) REFERENCES EMPRESA_CONTATO,
  CONSTRAINT EMEN_EMPR_FK FOREIGN KEY (EMPRESA_ENDERECO_ID) REFERENCES EMPRESA_ENDERECO
);

CREATE TABLE SETOR (
  ID INTEGER NOT NULL,
  TENANT_ID INTEGER NOT NULL,
  DESCRICAO VARCHAR(100) NOT NULL,
  NR_VERSAO INTEGER NOT NULL,
  DT_CADASTRO TIMESTAMP NOT NULL,
  DT_ULTIMA_ALTERACAO TIMESTAMP NOT NULL,
  IN_USO BOOLEAN NOT NULL,
  PRIMARY KEY(ID),
  CONSTRAINT TENA_EMPR_FK FOREIGN KEY (TENANT_ID) REFERENCES TENANT
);

CREATE TABLE CARGO (
  ID INTEGER NOT NULL,
  TENANT_ID INTEGER NOT NULL,
  DESCRICAO VARCHAR(100) NOT NULL,
  NR_VERSAO INTEGER NOT NULL,
  DT_CADASTRO TIMESTAMP NOT NULL,
  DT_ULTIMA_ALTERACAO TIMESTAMP NOT NULL,
  IN_USO BOOLEAN NOT NULL,
  PRIMARY KEY(ID),
  CONSTRAINT TENA_EMPR_FK FOREIGN KEY (TENANT_ID) REFERENCES TENANT
);

CREATE TABLE USUARIO_CONTATO (
  ID INTEGER NOT NULL,
  FONE_PESSOAL VARCHAR(45),
  FONE_COMERCIAL VARCHAR(45),
  FONE_CELULAR VARCHAR(45),
  FONE_OUTROS VARCHAR(45),
  EMAIL_PRINCIPAL VARCHAR(45),
  EMAIL_SECUNDARIO VARCHAR(45),
  NR_VERSAO INTEGER NOT NULL,
  DT_CADASTRO TIMESTAMP NOT NULL,
  DT_ULTIMA_ALTERACAO TIMESTAMP NOT NULL,
  IN_USO BOOLEAN NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE USUARIO_ENDERECO (
  ID INTEGER NOT NULL,
  CIDADE_ID INTEGER,
  RUA VARCHAR(50),
  NUMERO VARCHAR(10),
  COMPLEMENTO VARCHAR(100),
  BAIRRO VARCHAR(50),
  CEP VARCHAR(10),
  NR_VERSAO INTEGER NOT NULL,
  DT_CADASTRO TIMESTAMP NOT NULL,
  DT_ULTIMA_ALTERACAO TIMESTAMP NOT NULL,
  IN_USO BOOLEAN NOT NULL,
  PRIMARY KEY(ID),
  CONSTRAINT USEN_CIDA_FK FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE
);

CREATE TABLE USUARIO (
  ID INTEGER NOT NULL,
  TENANT_ID INTEGER NOT NULL,
  EMPRESA_ID INTEGER NOT NULL,
  CARGO_ID INTEGER,
  USUARIO_CONTATO_ID INTEGER,
  USUARIO_ENDERECO_ID INTEGER,
  SETOR_ID INTEGER,
  NOME VARCHAR(100) NOT NULL,
  LOGIN VARCHAR(50) NOT NULL,
  SENHA VARCHAR(50) NOT NULL,
  DT_NASCIMENTO DATE,
  DT_ADMISSAO DATE,
  NR_VERSAO INTEGER NOT NULL,
  DT_CADASTRO TIMESTAMP NOT NULL,
  DT_ULTIMA_ALTERACAO TIMESTAMP NOT NULL,
  IN_USO BOOLEAN NOT NULL,
  PRIMARY KEY(ID),
  CONSTRAINT TENA_EMPR_FK FOREIGN KEY (TENANT_ID) REFERENCES TENANT,
  CONSTRAINT EMPR_USUA_FK FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA,
  CONSTRAINT CARG_USUA_FK FOREIGN KEY (CARGO_ID) REFERENCES CARGO,
  CONSTRAINT USCO_USUA_FK FOREIGN KEY (USUARIO_CONTATO_ID) REFERENCES USUARIO_CONTATO,
  CONSTRAINT USEN_USUA_FK FOREIGN KEY (USUARIO_ENDERECO_ID) REFERENCES USUARIO_ENDERECO,
  CONSTRAINT SETO_USUA_FK FOREIGN KEY (SETOR_ID) REFERENCES SETOR
);

